### ISSUE TITLE
Build for MacOS

### ISSUE THREAD

**Issue by calebepb** [hpc-fci-mackenzie/PyDistance#8]
Why not add a CI that builds for MacOS?

**Comment by mvrozanti** [comment]
https://github.com/hpc-fci-mackenzie/PyDistance/blob/5d946db5ae045fff2aef023e4009746e611fb852/src/benchmark/benchmark.cpp#L8-L9

MacOS build is failing on an `std::aligned_alloc` call on the benchmark. According to the [documentation](https://en.cppreference.com/w/cpp/memory/c/aligned_alloc), it appears only as of C++17, even though it compiles fine on GNU g++ with C++11 (same happened in [this repo](https://github.com/marian-nmt/marian-dev/issues/227)).

### Edit:
replacing the call by `_mm_malloc` maintains performance and enables build on MacOS
