### ISSUE TITLE
CMakeLists without default condition

### ISSUE THREAD

**Issue by LeoFuso** [hpc-fci-mackenzie/PyDistance#9]
If you try to build the project without specifying the `REGISTER_WIDTH` it will throw an error.

Is not better if you rollback to `auto` mode, instead?

Just change de `else` condition in `CMakeLists` to configure for `auto`, instead of throwing an error.

**Comment by mvrozanti** [comment]
Can't reproduce
I was able to build on dev and master both

Make sure you're on https://github.com/hpc-fci-mackenzie/PyDistance/commit/0b849ea4ecd4ae86344c3aae1deb60b927969ac9

**Comment by LeoFuso** [comment]
Sorry, I've missed the line 47 in `CMakeLists`,
